version: "3.9"

services:
  mysql_db:
    image: mysql
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-"1234"}
    volumes:
      - railway_db:/var/lib/mysql

volumes:
  railway_db:
      name: railway_db
